apiVersion: v1
kind: LimitRange
metadata:
  name: minimum-limit-range
  namespace: demo-limitrange-violation
spec:
  limits:
  - type: Container
    min:
      cpu: "500m"
      memory: "24Mi"
    max:
      cpu: "1"
      memory: "32Gi"